### PR TITLE
Add missing keypad constants

### PR DESCRIPTION
**Pull request by viniciuslrangel**

### CODE REVIEW

**Comment by kwhat** [comment]
PR looks good, I need to do some testing and merge.

**Comment by vlad-velichko** [comment]
@kwhat please merge

**Comment by kwhat** [comment]
What platform are you testing on?  I cannot verify.

**Comment by kwhat** [comment]
Ive reverted this.  There are many issues including the collision with print screen.  Please open a bug report.  There is something else wrong here, they are not just missing.

**Pull request merged**
